"""Probe: one real GLM call with the judge prompt, dump RAW response to file."""
import json, os, urllib.request, sys

BASE = os.path.dirname(os.path.abspath(__file__))

def load_env():
    env = {}
    with open(os.path.join(BASE, ".env"), encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env

ENVV = load_env()
KEY = ENVV.get("GLM_CODING_TEAM2_KEY", "")

PROMPT = """You are normalizing mathematical problem statements for a research database.
For each numbered PAIR below, decide whether the two statements describe THE SAME
underlying mathematical problem (same canonical entry, possibly different wording,
generality, or context).
- "same": clearly the same problem
- "distinct": different mathematical problems
- "unsure": cannot decide from the given text

PAIR 1:
-- Statement A (paper 1111.0001):
Let X be a smooth projective variety. Is the rational cohomology H^*(X, Q) generated by algebraic cycles (the Hodge conjecture for X)?
-- Statement B (paper 2222.0002):
Does every smooth complex projective variety satisfy the Hodge conjecture in degree 2, i.e., are all Hodge classes of type (1,1) algebraic?

PAIR 2:
-- Statement A (paper 3333.0003):
Can every compact Kahler manifold be approximated by projective ones in the Gromov-Hausdorff sense?
-- Statement B (paper 4444.0004):
Is the fundamental group of every compact Kahler manifold residually finite?

Answer ONLY a JSON array in order:
[{"i": 1, "verdict": "same"|"distinct"|"unsure", "reason": "<one short sentence>"}, ...]"""

body = {"model": "glm-5.3",
        "messages": [{"role": "user", "content": PROMPT}],
        "max_tokens": 3000, "temperature": 0.1,
        "thinking": {"type": "disabled"}}
req = urllib.request.Request(
    "https://open.bigmodel.cn/api/coding/paas/v4/chat/completions",
    data=json.dumps(body).encode(), method="POST",
    headers={"Authorization": "Bearer " + KEY, "Content-Type": "application/json"})
try:
    with urllib.request.urlopen(req, timeout=300) as r:
        resp = json.load(r)
except urllib.error.HTTPError as e:
    print("HTTP", e.code, e.read().decode("utf-8", "replace")[:500])
    sys.exit(1)

with open(os.path.join(BASE, "probe_raw_response.json"), "w", encoding="utf-8") as f:
    json.dump(resp, f, ensure_ascii=False, indent=2)

msg = resp["choices"][0]["message"]
print("=== finish_reason:", resp["choices"][0].get("finish_reason"))
print("=== usage:", resp.get("usage"))
print("=== message keys:", list(msg.keys()))
print("=== content (first 800 chars):")
print((msg.get("content") or "<EMPTY>")[:800])
rc = msg.get("reasoning_content")
print("=== reasoning_content present:", bool(rc), "(len=%d)" % len(rc) if rc else "")
